// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("float");

                    b.Property<double>("Mileage")
                        .HasColumnType("float");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("SecondSpeed")
                        .HasColumnType("float");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("MakeId");

                    b.HasIndex("ModelId");

                    b.HasIndex("YearId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineId = 3,
                            MakeId = 1,
                            MaxSpeed = 260.0,
                            Mileage = 12.0,
                            ModelId = 2,
                            Name = "Audi Q5",
                            Price = 68.013999999999996,
                            SecondSpeed = 60.0,
                            YearId = 2
                        },
                        new
                        {
                            Id = 2,
                            EngineId = 7,
                            MakeId = 4,
                            MaxSpeed = 300.0,
                            Mileage = 60.0,
                            ModelId = 6,
                            Name = "Mercedes-Benz CLS 63 AMG S",
                            Price = 62.0,
                            SecondSpeed = 70.0,
                            YearId = 9
                        },
                        new
                        {
                            Id = 3,
                            EngineId = 3,
                            MakeId = 3,
                            MaxSpeed = 220.0,
                            Mileage = 180.0,
                            ModelId = 6,
                            Name = "Skoda Superb 2.0 TDI 4x4",
                            Price = 16.0,
                            SecondSpeed = 50.0,
                            YearId = 7
                        });
                });

            modelBuilder.Entity("Core.Entities.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cylinders")
                        .HasColumnType("int");

                    b.Property<int>("FuelConsumption")
                        .HasColumnType("int");

                    b.Property<double>("Horsepower")
                        .HasColumnType("float");

                    b.Property<string>("TypeEngine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Engines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cylinders = 2,
                            FuelConsumption = 5,
                            Horsepower = 60.0,
                            TypeEngine = "Diesel",
                            Volume = 1.3,
                            Weight = 220.0
                        },
                        new
                        {
                            Id = 2,
                            Cylinders = 3,
                            FuelConsumption = 6,
                            Horsepower = 140.0,
                            TypeEngine = "Petrol",
                            Volume = 1.5,
                            Weight = 240.0
                        },
                        new
                        {
                            Id = 3,
                            Cylinders = 4,
                            FuelConsumption = 8,
                            Horsepower = 180.0,
                            TypeEngine = "Petrol",
                            Volume = 2.0,
                            Weight = 350.0
                        },
                        new
                        {
                            Id = 4,
                            Cylinders = 5,
                            FuelConsumption = 9,
                            Horsepower = 220.0,
                            TypeEngine = "Petrol",
                            Volume = 2.2000000000000002,
                            Weight = 350.0
                        },
                        new
                        {
                            Id = 5,
                            Cylinders = 6,
                            FuelConsumption = 10,
                            Horsepower = 280.0,
                            TypeEngine = "Diesel",
                            Volume = 2.5,
                            Weight = 450.0
                        },
                        new
                        {
                            Id = 6,
                            Cylinders = 8,
                            FuelConsumption = 12,
                            Horsepower = 370.0,
                            TypeEngine = "Diesel",
                            Volume = 3.0,
                            Weight = 700.0
                        },
                        new
                        {
                            Id = 7,
                            Cylinders = 10,
                            FuelConsumption = 14,
                            Horsepower = 500.0,
                            TypeEngine = "Petrol",
                            Volume = 5.0,
                            Weight = 800.0
                        },
                        new
                        {
                            Id = 8,
                            Cylinders = 12,
                            FuelConsumption = 18,
                            Horsepower = 700.0,
                            TypeEngine = "Petrol",
                            Volume = 6.0,
                            Weight = 800.0
                        });
                });

            modelBuilder.Entity("Core.Entities.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Makes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Germany",
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Japan",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            Name = "Stellantis"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Germany",
                            Name = "Mercedes Benz"
                        },
                        new
                        {
                            Id = 5,
                            Country = "United States",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 6,
                            Country = "United States",
                            Name = "General Motors"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Japan",
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 8,
                            Country = "United States",
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Japan",
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 10,
                            Country = "China",
                            Name = "BYD Co. Ltd."
                        },
                        new
                        {
                            Id = 11,
                            Country = "Germany",
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("Core.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The most common car type is the sedan. A sedan is a four-door car type with a traditional trunk. The difference between a hatchback and a sedan is that the rear luggage compartment door does not include the rear window and the door hinges are installed under the window.",
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A crossover is often confused with an SUV. A crossover often comes as two-wheel drive, but it can also come with 4-wheel drive. It is basically an off-road car chassis, but built more for city traffic.",
                            Name = "Crossover (CUV)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Another type that climbs this list of car types is the SUV, which is becoming more and more popular. The SUV is a large car that can often carry five to seven passengers with three rows of seats. They are basically the same as a crossover, except that they are built on a body-on-frame chassis. They often have 4wd and good terrain capability.",
                            Name = "Sport Utility Vehicles (SUVs)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A Hatchback car is basically a mix of a sedan and a station wagon. They often come as a 5-door set and have a hatch that opens upwards. Like the station wagon, a hatchback has door hinges above the rear window.",
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A wagon is quite similar to a sedan, but with an extended roofline with a hatch door instead of a trunk. Station cars are often the perfect choice for families and long car journeys due to the larger cargo space than the sedan.",
                            Name = "Station Wagon"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The coupe is a two-door car, very similar to the sedan but with two doors instead of four. Coupé cars often have a rear seat for two or three more passengers, but you often have to fold down one of the front seats to get there. Coupé cars are often quite more towards the sporty look.",
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pickup trucks have become very common in recent years. A pickup has an enclosed cab with an open cargo area. They can either have space for two passengers or four. Pickup trucks have the cabin mounted on a separate steel frame, with one exception – Honda Ridgeline.",
                            Name = "Pickup Truck"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The minivan or multi-purpose vehicle (MPV) is a van, but instead of cargo space, it has passenger seats. It often has 7 or 8 passenger seats, making it perfect for larger families or being used as a taxi.",
                            Name = "Minivan (MPV)"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A roadster car is basically a convertible car, but with two doors, and it usually has no rear seat. They are therefore good for only two people. When it comes to size, they are often very small, with limited cargo space.",
                            Name = "Roadster"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A Van is a two- or three-seater car model that is often used to transport goods. They often have a sealed cab from the cargo area, and they often have no windows to the cargo area, but some models have glass windows at the rear doors.",
                            Name = "Van"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A sports car is anything that looks sporty to you, and it can be a roadster, coupe, or even a sedan. Sports cars are quite similar to the supercar, because a supercar can also be a sports car, but the difference is often that the sports car is a step below the supercar regarding performance and price.",
                            Name = "Sports Cars"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The supercar is a high-performance car, usually with a very powerful and large engine. Most supercars are two-seater and at the same time very expensive – some are going for as high as one million dollars.",
                            Name = "Supercar"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A luxury car is exactly what it sounds like – luxury. They are often very expensive, and have all the latest features for a comfortable ride. They often have a very powerful engine, but are not very fast in curves and on racetracks. This is because they often have so many features for comfort, so they are usually very heavy.",
                            Name = "Luxury Cars"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The convertible or cabriolet car models come with a retractable roof. They are the perfect choice for a hot summer day when you are going on holiday to the beach. Most convertible cars have an automatic system to retrace the fabric rooftop, but on some older models, you had to do this manually. Some models even have a retractable hardtop, which makes them look like normal cars when the rooftop is closed.",
                            Name = "Cabriolet"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Muscle cars are cars with large muscles under the hood. Muscle cars are often older American cars with very large and powerful v8 or v10 engines, but muscle cars are also available as modern cars. Muscle cars are usually not that fast on racetracks around corners, but when they drive in a straight line, like drag racing, not many other cars can beat them.",
                            Name = "Muscle Cars"
                        },
                        new
                        {
                            Id = 16,
                            Description = "The microcar or minicar is a small car that often comes with an engine size of less than a liter. They are available in various unusual designs and are ideal for city traffic due to their fuel efficiency and easy parking.",
                            Name = "Micro"
                        },
                        new
                        {
                            Id = 17,
                            Description = "A camper van is often a truck chassis that has been rebuilt for camping, and they often have a kitchen, toilet, and other necessary accessories for a perfect camping trip. For example, a motorhome can also refer to a minivan that has been rebuilt for camping, such as a Volkswagen transporter.",
                            Name = "Camper Van"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A mini truck is exactly what it sounds like – a small truck, and it’s a mix of a pickup and a truck. They often have two or three seats and open cargo space but can also come with closed cargo space.",
                            Name = "Mini Truck"
                        },
                        new
                        {
                            Id = 19,
                            Description = "A limousine is a stretched car that is often used by celebrities and pop stars. It has an elongated base and can be rebuilt from different car models.",
                            Name = "Limousine"
                        },
                        new
                        {
                            Id = 20,
                            Description = "In the last place on the list, you will find the truck. Although they are not really a car type, they can come in many forms and are still a vehicle type, so we wanted to include it.",
                            Name = "Truck"
                        },
                        new
                        {
                            Id = 21,
                            Description = "A hot hatch car is very similar to a hatchback car, which we talked about earlier in the article. However, a hot hatch is a hatchback that has been modified to improve performance and is generally a little more “sporty”.",
                            Name = "Hot Hatch"
                        },
                        new
                        {
                            Id = 22,
                            Description = "A grand tourer is typically a high-performance luxury car designed for long-distance driving. The term “grand tourer” or just “GT” is sometimes used to describe just a high-performance sports car, but the typical grand tourer is larger and more comfortable than a sports car.",
                            Name = "Grand Tourer"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Utes are popular in Australia and New Zealand, where they are often used as work vehicles. Ute is short for “coupé utility” or “utility”. Ute is a regular car that has been modified with a cargo bed in the back, instead of passenger seats. This makes it perfect for carrying large objects, such as timber or building materials.",
                            Name = "Ute"
                        },
                        new
                        {
                            Id = 24,
                            Description = "A military vehicle is exactly what it sounds like: a vehicle that is designed for or has been adapted to be used by the military. This includes tanks, armored personnel carriers, artillery, and other types of vehicles used by the military.",
                            Name = "Military Vehicle"
                        },
                        new
                        {
                            Id = 25,
                            Description = "A dragster is built to compete in drag racing. A typical drag race is a race in a straight line from one end of a track to another, and the goal is to reach the finish line first. To achieve this, dragsters rely on their incredible speed and acceleration, which is why some dragster cars have over 8,000 horsepower.",
                            Name = "Dragster"
                        });
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2023"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2022"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2021"
                        },
                        new
                        {
                            Id = 4,
                            Date = "2020"
                        },
                        new
                        {
                            Id = 5,
                            Date = "2019"
                        },
                        new
                        {
                            Id = 6,
                            Date = "2018"
                        },
                        new
                        {
                            Id = 7,
                            Date = "2017"
                        },
                        new
                        {
                            Id = 8,
                            Date = "2016"
                        },
                        new
                        {
                            Id = 9,
                            Date = "2015"
                        },
                        new
                        {
                            Id = 10,
                            Date = "2014"
                        },
                        new
                        {
                            Id = 11,
                            Date = "2013"
                        },
                        new
                        {
                            Id = 12,
                            Date = "2012"
                        },
                        new
                        {
                            Id = 13,
                            Date = "2011"
                        },
                        new
                        {
                            Id = 14,
                            Date = "2010"
                        },
                        new
                        {
                            Id = 15,
                            Date = "2009"
                        },
                        new
                        {
                            Id = 16,
                            Date = "2008"
                        },
                        new
                        {
                            Id = 17,
                            Date = "2007"
                        },
                        new
                        {
                            Id = 18,
                            Date = "2006"
                        },
                        new
                        {
                            Id = 19,
                            Date = "2005"
                        },
                        new
                        {
                            Id = 20,
                            Date = "2004"
                        },
                        new
                        {
                            Id = 21,
                            Date = "2003"
                        },
                        new
                        {
                            Id = 22,
                            Date = "2002"
                        },
                        new
                        {
                            Id = 23,
                            Date = "2001"
                        },
                        new
                        {
                            Id = 24,
                            Date = "2000"
                        },
                        new
                        {
                            Id = 25,
                            Date = "1999"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Car", b =>
                {
                    b.HasOne("Core.Entities.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Make", "Make")
                        .WithMany("Cars")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Year", "Year")
                        .WithMany("Cars")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Make");

                    b.Navigation("Model");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Engine", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Core.Entities.Make", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Core.Entities.Model", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Core.Entities.Year", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
